### ISSUE TITLE
Building Legacy Tensorflow

### ISSUE THREAD

**Issue by achintangal** [datamachines/cuda_tensorflow_opencv#19]
Is it possible to build with an older version of tensorflow 1.14.0? 
I changed the stable version of TF to this ^, but it fails to build and complains 

You have bazel 4.1.0 installed.
Please downgrade your bazel installation to version 0.25.2 or lower to build TensorFlow! To downgrade: download the installer for the old version 
(from https://github.com/bazelbuild/bazel/releases) then run the installer.
-- bazel command to run:
bazel build --verbose_failures --config=opt --config=v1 --config=cuda //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...

Changing the LATEST_BAZEL version in the makefile doesn't seem to work.

**Comment by mmartial** [comment]
I am unclear if this will work; mostly because recent packages/pip are not always compatible with older TF.

If you are trying to bypass the bazel selection logic, try to modify line 112 of  https://github.com/datamachines/cuda_tensorflow_opencv/blob/master/ubuntu18.04/Dockerfile so that the `.bazelversion` file contains the bazel version you need (`0.25.2`)

Another method might have you dig into the `Dockerfile` that worked for a previous 1.14 build; check https://github.com/datamachines/cuda_tensorflow_opencv/blob/master/Builds-DockerHub.md and click on the Github link for the version that worked at the time that is closest to your need, you should see the `Makefile` used at the time.

Finally, if a tag is listed in https://github.com/datamachines/cuda_tensorflow_opencv/blob/master/Builds-DockerHub.md that you can use, it is likely still available on Dockerhub to `docker pull` directly

**Comment by achintangal** [comment]
Thanks for this! 
I ended up using the older repo's example and worked around the problem by switching to tensorflow's docker image. (tensforflow/tensorflow-1.14.0-gpu) 
I am yet to get this completely working with opencv though.

**Comment by mmartial** [comment]
I checked `docker run --rm -it tensorflow/tensorflow:1.14.0-gpu-py3 /bin/bash` and it runs `Ubuntu 18.04.2 LTS` (with Python 3.6.8) so in theory, you could copy a good chunk of the `Ubuntu18.04/Dockerfile`,  replace the `FROM` to use `tensorflow/tensorflow:1.14.0-gpu-py3` remove the entire TF build section and you should be able to get OpenCV working.

Another option is to follow the instructions to install 1.14 GPU using `pip` at https://www.tensorflow.org/install/pip and replace the entire "building" code with a simple `pip install` in the `Ubuntu18.04/Dockerfile` 

I have not tested, so I can not say it will work, but those are fairly simple tests you need to build GPU OpenCV

**Comment by mmartial** [comment]
> I ended up using the older repo's example and worked around the problem by switching to tensorflow's docker image. (tensforflow/tensorflow-1.14.0-gpu)

Closing this issue based on the above comment and the instructions provided in https://github.com/datamachines/cuda_tensorflow_opencv/issues/19#issuecomment-851147417
