### ISSUE TITLE
Unraid python3 packages on restart

### ISSUE THREAD

**Issue by ghzgod** [datamachines/cuda_tensorflow_opencv#30]
Pardon my ignorance.

I have to pip install some packages for my use case.  As some of you know, after a docker restart the packages are not there anymore and have to be reinstalled.

Is there a way to keep my installed packages (apt-get or pip) to remain persistent on docker reboot?

Thank you!

**Comment by mmartial** [comment]
Unraid is a special case. 
Doing [`virtualenv`](https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/) adds in the `/dmc` directory will support the `pip3` installs but not the `apt-get` ones (and new releases might not work with your custom installs).

Outside of Unraid, the way to extend the container is to create your own specialized version by `docker build` `FROM` it and add your needed tools to it.

I tried this by `docker build -t my_jto:latest .` the following `Dockerfile` from a terminal on the server (adapt with `CuDNN` if that is your version):
```
FROM datamachines/jupyter_to-unraid:2.8.0_4.5.5-20220318

ARG DEBIAN_FRONTEND=noninteractive

USER jupyter
RUN sudo apt-get install -y emacs-nox

WORKDIR /dmc
EXPOSE 8888
CMD jupyter-notebook --ip=0.0.0.0 --port=8888 --no-browser
```
Notes:
- for `FROM` I avoided `latest` in favor of the same digest entry that is installed from the tags at https://hub.docker.com/r/datamachines/jupyter_to-unraid/tags 
- the `jupyter` user can `sudo` so installs are done this way
- the last 3 lines make `jupyter-notebook` start in `/dmc` and make sure the port is exposed

Doing this, the `Advanced View` in the `Docker` tab shows me an `Orphan Image`, so it is a matter of creating a new template for this image in the `/boot/config/plugins/dockerMan` directory.

Before this, I also will mention that if you want to save an already running image, you can [`docker commit`](https://docs.docker.com/engine/reference/commandline/commit/) its digest into a new image name. This way all the installs you did inside the running container are preserved in a new image, but it too will show as an `Orphan Image` until a template is created for it.

Related to the template, I have tested the following successfully (following the `Dockerfile` build use case):
- in `/boot/config/plugins/dockerMan/templates-user`, `cp my-Jupyter-TensorFlow_OpenCV.xml my-My-Jupyter-TensorFlow_OpenCV.xml`
- in the `Docker` tab, `Add Container` and use the newly available `My-Jupyter-TensorFlow_OpenCV`
- edit the `Name` to be `My-Jupyter-TensorFlow_OpenCV`. This is important because if you have a `Jupter-TensorFlow-OpenCV` version already installed, it will overwrite that template when you apply otherwise (ie the filename use this `Name`)
- change the `Repository` to be the image recently built: `my_jto:latest`
- remove the content of the `Docker Hub URL` to avoid it being updatable
- Change the `WebUI` port to be one not already in use
- Click the `Apply` button and you should have a `My-Jupyter-TensorFlow_OpenCV` available to use with all the customizations you did (from my `Dockerfile` example, `emacs` is now installed)

On the `Docker` tab, a `not available` will be in the `VERSION` column, which is normal: the container can not be updated automatically.

Repeat this process for as many custom installs as you need. Because this is docker image, only the modified layers will take space on your server.

**Comment by mmartial** [comment]
I have added a new section on the Unraid Support Thread at https://forums.unraid.net/topic/121930-support-jupyter-tensorflow_opencv-and-jupyter-cudnn_tensorflow_opencv/ that covers "Persisting user's installs/changes" based on these instructions.

Let me know if you are okay to close this at this point.

**Comment by ghzgod** [comment]
First let me say, thank you for the detailed write up. Wow!  You don't even know who I am yet you took the time to explain all this to me.  I really appreciate that.  I will close the issue here.  You have allowed me to further progress my passion!  Machine learning. Thank you!

**Comment by mmartial** [comment]
My pleasure :)

Note that the unraid support thread instructions are likely more specific to your potential use case (`docker commit` based).
